from django.urls import path

from .views import (
    AdminAppLoginView,
    AdminAppLogoutView,
    CategoryAssignModeratorView,
    CategoryUnassignModeratorView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryListView,
    CategoryReorderView,
    CategoryToggleStatusView,
    CategoryUpdateView,
    CommentCreateView,
    CommentDeleteView,
    CommentListView,
    CommentToggleStatusView,
    CommentUpdateView,
    DashboardView,
    MediaLibraryView,
    PageCreateView,
    PageDeleteView,
    PageListView,
    PageToggleStatusView,
    PageUpdateView,
    PostCreateView,
    PostDeleteView,
    PostDetailView,
    PostCommentDeleteBranchView,
    PostListView,
    PostToggleStatusView,
    PostUpdateView,
    ReportCreateView,
    ReportDeleteView,
    ReportApproveView,
    ReportRejectView,
    ReportListView,
    ReportUpdateView,
    SettingsView,
    TagCreateView,
    TagDeleteView,
    TagListView,
    TagUpdateView,
    UserCreateView,
    UserDeleteView,
    UserListView,
    UserSeedCreateView,
    UserSeedDeleteView,
    UserUpdateView,
)

app_name = "admin_app"

urlpatterns = [
    path("login/", AdminAppLoginView.as_view(), name="login"),
    path("logout/", AdminAppLogoutView.as_view(), name="logout"),
    path("", DashboardView.as_view(), name="dashboard"),
    path("media/", MediaLibraryView.as_view(), name="media-library"),
    path("posts/", PostListView.as_view(), name="post-list"),
    path("posts/create/", PostCreateView.as_view(), name="post-create"),
    path("posts/<str:document_id>/view/", PostDetailView.as_view(), name="post-detail"),
    path("posts/<str:document_id>/edit/", PostUpdateView.as_view(), name="post-update"),
    path("posts/<str:document_id>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("posts/<str:document_id>/comments/<str:comment_document_id>/delete-branch/", PostCommentDeleteBranchView.as_view(), name="post-comment-delete-branch"),
    path("posts/<str:document_id>/toggle-status/", PostToggleStatusView.as_view(), name="post-toggle-status"),
    path("pages/", PageListView.as_view(), name="page-list"),
    path("pages/create/", PageCreateView.as_view(), name="page-create"),
    path("pages/<str:document_id>/edit/", PageUpdateView.as_view(), name="page-update"),
    path("pages/<str:document_id>/delete/", PageDeleteView.as_view(), name="page-delete"),
    path("pages/<str:document_id>/toggle-status/", PageToggleStatusView.as_view(), name="page-toggle-status"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/reorder/", CategoryReorderView.as_view(), name="category-reorder"),
    path("categories/create/", CategoryCreateView.as_view(), name="category-create"),
    path("categories/<str:document_id>/edit/", CategoryUpdateView.as_view(), name="category-update"),
    path("categories/<str:document_id>/delete/", CategoryDeleteView.as_view(), name="category-delete"),
    path("categories/<str:document_id>/toggle-status/", CategoryToggleStatusView.as_view(), name="category-toggle-status"),
    path("categories/<str:document_id>/assign-moderator/", CategoryAssignModeratorView.as_view(), name="category-assign-moderator"),
    path("categories/unassign-moderator/<int:assignment_id>/", CategoryUnassignModeratorView.as_view(), name="category-unassign-moderator"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<str:document_id>/edit/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<str:document_id>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("comments/", CommentListView.as_view(), name="comment-list"),
    path("comments/create/", CommentCreateView.as_view(), name="comment-create"),
    path("comments/<str:document_id>/edit/", CommentUpdateView.as_view(), name="comment-update"),
    path("comments/<str:document_id>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
    path("comments/<str:document_id>/toggle-status/", CommentToggleStatusView.as_view(), name="comment-toggle-status"),
    path("reports/", ReportListView.as_view(), name="report-list"),
    path("reports/create/", ReportCreateView.as_view(), name="report-create"),
    path("reports/<str:document_id>/edit/", ReportUpdateView.as_view(), name="report-update"),
    path("reports/<str:document_id>/delete/", ReportDeleteView.as_view(), name="report-delete"),
    path("reports/<str:document_id>/approve/", ReportApproveView.as_view(), name="report-approve"),
    path("reports/<str:document_id>/reject/", ReportRejectView.as_view(), name="report-reject"),
    path("users/", UserListView.as_view(), name="user-list"),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
    path("users/<str:document_id>/edit/", UserUpdateView.as_view(), name="user-update"),
    path("users/<str:document_id>/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("users/seed/", UserSeedCreateView.as_view(), name="user-seed"),
    path("users/seed/delete/", UserSeedDeleteView.as_view(), name="user-seed-delete"),
    path("settings/", SettingsView.as_view(), name="settings"),
]
