# Generated by Django 6.0.3 on 2026-03-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(default='gpt-5.4', max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('content_prompt', models.TextField(blank=True)),
                ('comment_prompt', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GA4AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(blank=True, max_length=255)),
                ('measurement_id', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True)),
                ('is_connected', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
