# Generated by Django 6.0.3 on 2026-03-28 07:54

import trekky_apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiautomationsettings',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='aiautomationsettings',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='aiautomationsettings',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='aiautomationsettings',
            name='provider',
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='anthropic_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='anthropic_models',
            field=models.JSONField(blank=True, default=trekky_apps.integrations.models.default_anthropic_models),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_allow_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_cron',
            field=models.CharField(default='0 */6 * * *', max_length=100),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='comments_per_run',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_category_document_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_cron',
            field=models.CharField(default='0 */6 * * *', max_length=100),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_image_count_max',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_image_count_min',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_image_provider',
            field=models.CharField(choices=[('auto', 'Auto'), ('google', 'Google'), ('pexels', 'Pexels')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_last_scenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_posts_per_run',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_preferred_media_mode',
            field=models.CharField(choices=[('body', 'Body'), ('gallery', 'Gallery')], default='body', max_length=20),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='content_scenario_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='google_image_search_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='google_image_search_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='google_image_search_engine_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='openai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='openai_models',
            field=models.JSONField(blank=True, default=trekky_apps.integrations.models.default_openai_models),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='pexels_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='pexels_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='reply_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiautomationsettings',
            name='timezone',
            field=models.CharField(default='Asia/Ho_Chi_Minh', max_length=64),
        ),
    ]
