# Generated by Django 6.0.3 on 2026-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_mediastoragesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('redirect_uri', models.CharField(blank=True, default='http://localhost:8000/api/v1/auth/google/callback/', max_length=500)),
                ('frontend_url', models.CharField(blank=True, default='http://localhost:3000', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
