# Generated by Django 6.0.3 on 2026-04-07 07:42

import trekky_apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_google_oauth_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_timeout', models.PositiveIntegerField(default=30)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, default='Trekky', max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('frontend_base_url', models.CharField(blank=True, default='http://localhost:3001', max_length=500)),
                ('login_path', models.CharField(blank=True, default='/', max_length=255)),
                ('password_reset_path', models.CharField(blank=True, default='/reset-password', max_length=255)),
                ('registration_email_subject', models.CharField(blank=True, default=trekky_apps.integrations.models.default_registration_email_subject, max_length=255)),
                ('registration_email_body', models.TextField(blank=True, default=trekky_apps.integrations.models.default_registration_email_body)),
                ('password_reset_email_subject', models.CharField(blank=True, default=trekky_apps.integrations.models.default_password_reset_email_subject, max_length=255)),
                ('password_reset_email_body', models.TextField(blank=True, default=trekky_apps.integrations.models.default_password_reset_email_body)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
