# Generated by Django 6.0.3 on 2026-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='action_type',
            field=models.CharField(choices=[('like', 'Like'), ('share', 'Share'), ('save', 'Save'), ('follow', 'Follow')], max_length=20),
        ),
    ]
