# Generated by Codex on 2026-03-28

from django.db import migrations, models


def seed_existing_categories_as_published(apps, schema_editor):
    Category = apps.get_model("taxonomy", "Category")
    Category.objects.filter(status="draft").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_existing_categories_as_published, migrations.RunPython.noop),
    ]
