# Generated by Django 6.0.3 on 2026-03-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=50)),
                ('target_document_id', models.CharField(db_index=True, max_length=24)),
                ('action', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeratorCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_assignments', to='taxonomy.category')),
                ('moderator', models.ForeignKey(limit_choices_to={'role': 'moderator'}, on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('moderator', 'category')},
            },
        ),
    ]
